name: medijobsconnect
description: "A flutter web app for Medijobs Connect."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  flutter_datetime_picker_plus: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
  # Add Firebase dependencies
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.0  # Optional but recommended for user data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
